// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwyECQTCd_xeCGJTEYsLCrDQzMvF1y5Ls',
    appId: '1:674837851111:android:75b8d6edfc86d5cbbe6b42',
    messagingSenderId: '674837851111',
    projectId: 'petg-a6dea',
    storageBucket: 'petg-a6dea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCnfxzaVPZIMHZpmKayDMA8IGvNHfcjsI',
    appId: '1:674837851111:ios:00a0c5f9af6eb25ebe6b42',
    messagingSenderId: '674837851111',
    projectId: 'petg-a6dea',
    storageBucket: 'petg-a6dea.firebasestorage.app',
    androidClientId: '674837851111-gp02ii14q369gqltvelnadnmit2uhrca.apps.googleusercontent.com',
    iosClientId: '674837851111-6424e3io5pb34ntco107vum5p7ludpn3.apps.googleusercontent.com',
    iosBundleId: 'com.petg',
  );
}
